### ISSUE TITLE
App is not launching because of pod install error

### ISSUE THREAD

**Issue by DevarshiK** [upnext/BeaconCtrl_iOS_sample_app#2]
I tried to use this sample app by initiating a pod install but is failing with below error:

<img width="563" alt="screen shot 2016-06-09 at 1 36 07 pm" src="https://cloud.githubusercontent.com/assets/18421257/15922777/29406718-2e47-11e6-8b1f-c8218199306e.png">

Any ideas?

**Comment by otrebmuh** [comment]
Hello,

We were able to compile the application by linking the static library, go here:

https://www.mapbox.com/mapbox-ios-sdk-legacy/api/

In the "Installation" section, click on "static library" and you will find the file Mapbox-iOS-SDK-1.6.0.zip which you can then use to compile the app.

Best regards,

Humberto

**Comment by yltou** [comment]
Hi,

I have same problem to run the sample app as well.

**Comment by yltou** [comment]
Hi,

I'm having problem for trying this sample app as well.
Linked the static library for Mapbox but still not working.

![screen shot 2016-07-18 at 11 07 50 am](https://cloud.githubusercontent.com/assets/20161489/16905406/0a9755b0-4cd8-11e6-91e3-c62cba10e3cf.png)

Any help will be appreciated, thanks

**Comment by tkantonio** [comment]
Mapbox 1.6.0.is depreciated now. This will do the trick in your pod file (there is source stored somewhere else):
`pod 'Mapbox-iOS-SDK', :git => "https://github.com/OrdnanceSurvey/mapbox-ios-sdk.git", :branch => :release`

**Comment by alliance3** [comment]
I have a problem, some error, I'm not master in xcode development, so if someone can help me.
![capture 2016-11-08 a 11 10 28](https://cloud.githubusercontent.com/assets/16987876/20095055/2763db76-a5a4-11e6-96db-aa5ba39ba2c5.jpg)
![capture 2016-11-08 a 11 10 33](https://cloud.githubusercontent.com/assets/16987876/20095061/2c7eabe0-a5a4-11e6-81fa-f203e9c002b2.jpg)

**Comment by aachojnacki** [comment]
For now, we've solved this by using mapbox 1.6 from another repo
